{% set name = "yggdrasil-rapidjson" %}
{% set version = "1.1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - cmake >=3.15                           # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - numpy >=1.13.0                         # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake >=3.15
    - ninja
    - numpy >=1.13.0
    - python
  run:
    - numpy >=1.13.0
    - python

test:
  commands:
    - test -f $PREFIX/lib/cmake/YggdrasilRapidJSON/YggdrasilRapidJSONConfig.cmake  # [unix]
    - test -f $PREFIX/lib/cmake/YggdrasilRapidJSON/YggdrasilRapidJSONConfigVersion.cmake  # [unix]
    - test -f $PREFIX/include/yggdrasil_rapidjson/rapidjson/rapidjson.h  # [unix]
    - if not exist %LIBRARY_PREFIX%\\cmake\\YggdrasilRapidJSONConfig.cmake exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\cmake\\YggdrasilRapidJSONConfigVersion.cmake exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\include\\yggdrasil_rapidjson\\rapidjson\\rapidjson.h exit 1  # [win]
  source_files:
    - example
  requires:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

about:
  home: https://github.com/cropsinsilico/yggdrasil-rapidjson
  license: MIT
  license_file: license.txt
  summary: |
    A header-only C++ library for JSON operation extended for use with
    yggdrasil

extra:
  recipe-maintainers:
    - langmm
