import json
import argparse
from urllib.request import urlopen


if __name__ == "__main__":
    parser = argparse.ArgumentParser("Create a C++ header file containing "
                                     "the YGGDRASIL schema")
    parser.add_argument("dest",
                        help=("Path to header file where the metaschema "
                              "should be saved."))
    parser.add_argument("--base-draft", default="draft-04",
                        help="JSON schema draft that should be used as a base")
    args = parser.parse_args()
    url = f'http://json-schema.org/{args.base_draft}/schema#'
    base = json.loads(urlopen(url).read().decode('utf-8'))
    base['title'] = "Ygg meta-schema for data type schemas"
    base['definitions']['simpleTypes']['enum'] += [
        "1darray", "any", "bytes", "class", "complex", "float",
        "function", "instance", "int", "ndarray", "obj", "ply",
        "scalar", "schema", "uint", "unicode"]
    base['properties'].update({
        "args": {
            "description": "Arguments required to recreate a class instance.",
            "type": "array"
        },
        "class": {
            "anyOf": [
                {"type": "class"},
                {"items": {"type": "class"},
                 "minItems": 1,
                 "type": "array"}],
            "description": "One or more classes that the object should be an instance of."
        },
        "kwargs": {
            "description": "Keyword arguments required to recreate a class instance.",
            "type": "object"
        },
        "length": {
            "description": "Number of elements in the 1D array.",
            "minimum": 1,
            "type": "number"
        },
        "precision": {
            "description": "The size (in bits) of each item.",
            "minimum": 1,
            "type": "number"
        },
        "shape": {
            "description": "Shape of the ND array in each dimension.",
            "items": {
                "minimum": 1,
                "type": "integer"
            },
            "type": "array"
        },
        "subtype": {
            "description": "The base type for each item.",
            "enum": [
                "bytes",
                "complex",
                "float",
                "int",
                "uint",
                "unicode"
            ],
            "type": "string"
        },
        "units": {
            "description": "Physical units.",
            "type": "string"
        },
        "aliases": {
            "description": "Aliases for a property that also be used.",
            "type": "array",
            "items": {"type": "string"}
        },
    })
    contents = ["// This file is generated by create_metaschema.py do not modify directly", "",
                "#ifndef METASCHEMA_H_",
                "#define METASCHEMA_H_", "",
                "template<class T>",
                "struct item_return{ typedef T type; };", "",
                "template<typename T>",
                "inline const typename item_return<T>::type* get_metaschema() { return nullptr; }", "",
                "template<>",
                "inline const item_return<char>::type* get_metaschema<char>() {",
                "  const char* out = \""
                + json.dumps(base, indent=1).replace(
                    "\"", "\\\"").replace('\n', "\"\n    \"") + "\";",
                "  return out;",
                "};", "",
                "template<>",
                "inline const item_return<wchar_t>::type* get_metaschema<wchar_t>() {",
                "  const wchar_t* out = L\""
                + json.dumps(base, indent=1).replace(
                    "\"", "\\\"").replace('\n', "\"\n    L\"") + "\";",
                "  return out;",
                "};", "",
                "", "#endif // METASCHEMA_H_"]
    with open(args.dest, 'w') as fd:
        fd.write('\n'.join(contents))
