var dir_32fb88e4d38e67d524aa70efbc36f66b =
[
    [ "error", "dir_5937892b65cdaf02cc4201f920170bd1.html", "dir_5937892b65cdaf02cc4201f920170bd1" ],
    [ "internal", "dir_8d7584a8244d286291cd37b99676a43b.html", "dir_8d7584a8244d286291cd37b99676a43b" ],
    [ "allocators.h", "allocators_8h_source.html", null ],
    [ "base64.h", "base64_8h_source.html", null ],
    [ "cursorstreamwrapper.h", "cursorstreamwrapper_8h_source.html", null ],
    [ "document.h", "document_8h.html", "document_8h" ],
    [ "encodedstream.h", "encodedstream_8h_source.html", null ],
    [ "encodings.h", "encodings_8h_source.html", null ],
    [ "filereadstream.h", "filereadstream_8h_source.html", null ],
    [ "filewritestream.h", "filewritestream_8h_source.html", null ],
    [ "fwd.h", "fwd_8h_source.html", null ],
    [ "helpers.h", "helpers_8h_source.html", null ],
    [ "istreamwrapper.h", "istreamwrapper_8h_source.html", null ],
    [ "memorybuffer.h", "memorybuffer_8h_source.html", null ],
    [ "memorystream.h", "memorystream_8h_source.html", null ],
    [ "metaschema.h", "metaschema_8h_source.html", null ],
    [ "npy_2_compat.h", "npy__2__compat_8h_source.html", null ],
    [ "obj.h", "obj_8h_source.html", null ],
    [ "ostreamwrapper.h", "ostreamwrapper_8h_source.html", null ],
    [ "ply.h", "ply_8h_source.html", null ],
    [ "pointer.h", "pointer_8h_source.html", null ],
    [ "precision.h", "precision_8h.html", null ],
    [ "prettywriter.h", "prettywriter_8h_source.html", null ],
    [ "pyrj.h", "pyrj_8h_source.html", null ],
    [ "pyrj_c.h", "pyrj__c_8h_source.html", null ],
    [ "pythoncapi_compat.h", "pythoncapi__compat_8h_source.html", null ],
    [ "rapidjson.h", "rapidjson_8h.html", "rapidjson_8h" ],
    [ "reader.h", "reader_8h.html", "reader_8h" ],
    [ "schema.h", "schema_8h_source.html", null ],
    [ "stream.h", "stream_8h_source.html", null ],
    [ "stringbuffer.h", "stringbuffer_8h_source.html", null ],
    [ "units.h", "units_8h_source.html", null ],
    [ "uri.h", "uri_8h_source.html", null ],
    [ "va_list.h", "va__list_8h_source.html", null ],
    [ "writer.h", "writer_8h_source.html", null ]
];