c_stdlib:
  - sysroot                     # [linux]
  - macosx_deployment_target    # [osx]
  - vs                          # [win]
c_stdlib_version:
  - 2.17                        # [linux]
  - 11                          # [osx]
c_compiler:
  - gcc                         # [linux]
  - clang                       # [osx]
  - vs2017                      # [win]
cxx_compiler:
  - gxx                         # [linux]
  - clangxx                     # [osx]
  - vs2017                      # [win]
