context:
  version: "1.1.0.4"

package:
  name: yggdrasil-rapidjson
  version: ${{ version }}

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - cmake >=3.18
    - ninja
    - if: build_platform != host_platform
      then:
        - cross-python_${{ host_platform }}
        - python
        - numpy
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - numpy
  run:
    - python
    - numpy

tests:
  - package_contents:
      files:
        - if: win
          then:
            - Library/cmake/YggdrasilRapidJSONConfig.cmake
            - Library/cmake/YggdrasilRapidJSONConfigVersion.cmake
            - Library/cmake/YggdrasilRapidJSONMacros.cmake
        - if: unix
          then:
            - lib/cmake/YggdrasilRapidJSON/YggdrasilRapidJSONConfig.cmake
            - lib/cmake/YggdrasilRapidJSON/YggdrasilRapidJSONConfigVersion.cmake
            - lib/cmake/YggdrasilRapidJSON/YggdrasilRapidJSONMacros.cmake
      include:
        - yggdrasil_rapidjson/yggdrasil_rapidjson.h
  - script:
      - if: unix
        then: tests/run_test.sh
      - if: win
        then: tests/run_test.bat
    requirements:
      run:
        - ${{ stdlib('c') }}
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - cmake >=3.18
        - ninja
    files:
      source:
        - example/

about:
  homepage: https://github.com/cropsinsilico/yggdrasil-rapidjson
  repository: https://github.com/cropsinsilico/yggdrasil-rapidjson
  summary: |
    A header-only C++ library for JSON operation extended for use with
    yggdrasil
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - langmm
